import type { Metadata } from 'next';
import { Button, Footer, Header, PageShell, SectionLabel } from '../components';
import { formats } from '../../lib/interprete/marketing';
import { contactUrl } from '../../lib/contact';
import { pageMetadata } from '../../lib/seo';
import { Reveal } from '../motion';
import { StudyIcon } from '../visuals';

export const metadata: Metadata = pageMetadata({ title: 'Formatos', description: 'Conheça os formatos de acompanhamento do Interprete.', pathname: '/planos' });

export default function PlansPage() {
  return <PageShell><Header /><main className="it-info-page it-plans-page"><section className="it-subpage-hero"><div className="it-container it-subpage-hero-layout"><Reveal as="div" className="it-subpage-copy" stagger><div className="it-hero-kicker"><SectionLabel>Interprete. / formatos</SectionLabel><span>percurso de 12 semanas</span></div><h1>Escolha o ritmo que combina com o seu momento.</h1><p>Todos os formatos começam com um encontro inicial e organizam 12 semanas de estudo. A diferença está na frequência de encontros mensais.</p></Reveal><Reveal as="div" className="it-subpage-index" stagger><span>01</span><StudyIcon name="route" size={52} /><p>um formato é uma forma de sustentar a pergunta no tempo</p></Reveal></div></section><section className="it-formats-section" aria-labelledby="plans-title"><div className="it-container"><Reveal as="div" className="it-section-lead it-section-lead--wide" stagger><div><SectionLabel>ritmo de acompanhamento</SectionLabel><h2 id="plans-title">Três formas de continuar estudando.</h2></div><p>Converse sobre seu ponto de partida antes de escolher. O formato é uma decisão de ritmo, não uma promessa de resultado.</p></Reveal><Reveal as="div" className="it-format-layout" stagger>{formats.map((format, index) => <article className={index === 1 ? 'it-format-card it-format-card--primary' : 'it-format-card'} key={format.name}><div className="it-format-topline"><span>0{index + 1}</span><span>12 semanas</span></div><span className="it-format-kicker">{format.kicker}</span><h3>{format.name}</h3><p>{format.audience}</p><div className="it-format-value"><s>{format.previousPrice}</s><strong>{format.price}</strong></div><span className="it-format-cadence">{format.cadence}</span><a className="it-button" href={contactUrl()} target="_blank" rel="noreferrer">Conversar sobre este formato <StudyIcon name="arrow" size={17} /></a></article>)}</Reveal></div></section><section className="it-info-callout"><Reveal as="div" className="it-container it-callout-inner" stagger><div><SectionLabel>antes de decidir</SectionLabel><h2>Uma boa escolha começa pela conversa certa.</h2><p>Conte o que você quer entender e descubra qual formato faz sentido para seu momento.</p></div><Button href={contactUrl()}>Conversar agora</Button></Reveal></section></main><Footer /></PageShell>;
}
