/** Typed bridge for JS libraries and Tailwind v3 compatibility.
 * Tailwind v4 projects should use tokens.css as the source of truth.
 */

export const gsPrimitives = {
  "global_paper_0": "#FFFDF8",
  "global_paper_50": "#F7F2E8",
  "global_paper_100": "#EEE7DA",
  "global_paper_200": "#E1D7C7",
  "global_ink_950": "#1B1A17",
  "global_ink_800": "#34322D",
  "global_ink_600": "#615E56",
  "global_ink_500": "#777269",
  "home_background": "#F6F1E7",
  "home_surface": "#FFFCF7",
  "home_text": "#27241F",
  "home_muted": "#665F56",
  "home_primary": "#2A2722",
  "home_nutrition": "#28543E",
  "home_interprete": "#83501E",
  "home_border": "#D8CDBD",
  "home_focus": "#075EA8",
  "nutrition_background": "#F2F3EA",
  "nutrition_surface": "#FCFBF5",
  "nutrition_text": "#1D2A23",
  "nutrition_muted": "#59645D",
  "nutrition_primary": "#1F4A37",
  "nutrition_primaryHover": "#173B2C",
  "nutrition_accent": "#71846A",
  "nutrition_accentSoft": "#DDE5D7",
  "nutrition_clay": "#9B5F47",
  "nutrition_border": "#C8D0C3",
  "nutrition_focus": "#0B665A",
  "nutrition_dark": "#10261C",
  "nutrition_darkText": "#F2F5EC",
  "nutrition_darkMuted": "#C6D0C7",
  "nutrition_darkAccent": "#B8C7AA",
  "nutrition_darkCta": "#D6A17E",
  "interprete_background": "#F4EDE1",
  "interprete_surface": "#FCF8F0",
  "interprete_text": "#251B13",
  "interprete_muted": "#68594C",
  "interprete_primary": "#4A2F1C",
  "interprete_primaryHover": "#3B2517",
  "interprete_accent": "#7C4A12",
  "interprete_accentSoft": "#E9D6B3",
  "interprete_ochre": "#AA722A",
  "interprete_charcoal": "#211C18",
  "interprete_border": "#D8C7AF",
  "interprete_focus": "#A34F0A",
  "interprete_dark": "#1E1813",
  "interprete_darkText": "#F6EEDC",
  "interprete_darkMuted": "#C9B9A4",
  "interprete_darkAccent": "#D5A85C",
  "status_success": "#256D4B",
  "status_warning": "#81550C",
  "status_error": "#9B2F35",
  "status_info": "#2B5B7C"
} as const

export const gsTheme = {
  colors: {
    background: "var(--theme-background)",
    foreground: "var(--theme-text)",
    surface: "var(--theme-surface)",
    "surface-muted": "var(--theme-surface-muted)",
    primary: "var(--theme-primary)",
    "primary-hover": "var(--theme-primary-hover)",
    "primary-foreground": "var(--theme-primary-foreground)",
    accent: "var(--theme-accent)",
    "accent-warm": "var(--theme-accent-warm)",
    border: "var(--theme-border)",
    focus: "var(--theme-focus)",
    success: "var(--gs-status-success)",
    warning: "var(--gs-status-warning)",
    error: "var(--gs-status-error)",
    info: "var(--gs-status-info)",
  },
  fontFamily: {
    sans: ["var(--gs-font-body)"],
    serif: ["var(--gs-font-display)"],
    mono: ["var(--gs-font-mono)"],
  },
  fontSize: {
    display: ["var(--type-display-size)", { lineHeight: "var(--type-display-line)", letterSpacing: "var(--type-display-tracking)", fontWeight: "var(--type-display-weight)" }],
    "page-title": ["var(--type-page-title-size)", { lineHeight: "var(--type-page-title-line)", letterSpacing: "var(--type-page-title-tracking)", fontWeight: "var(--type-page-title-weight)" }],
    "section-title": ["var(--type-section-title-size)", { lineHeight: "var(--type-section-title-line)", letterSpacing: "var(--type-section-title-tracking)", fontWeight: "var(--type-section-title-weight)" }],
    lead: ["var(--type-lead-size)", { lineHeight: "var(--type-lead-line)", letterSpacing: "var(--type-lead-tracking)", fontWeight: "var(--type-lead-weight)" }],
    body: ["var(--type-body-size)", { lineHeight: "var(--type-body-line)", letterSpacing: "var(--type-body-tracking)", fontWeight: "var(--type-body-weight)" }],
    "body-compact": ["var(--type-body-compact-size)", { lineHeight: "var(--type-body-compact-line)", fontWeight: "var(--type-body-compact-weight)" }],
    ui: ["var(--type-ui-size)", { lineHeight: "var(--type-ui-line)", fontWeight: "var(--type-ui-weight)" }],
    nav: ["var(--type-nav-size)", { lineHeight: "var(--type-nav-line)", fontWeight: "var(--type-nav-weight)" }],
    button: ["var(--type-button-size)", { lineHeight: "var(--type-button-line)", fontWeight: "var(--type-button-weight)" }],
    label: ["var(--type-label-size)", { lineHeight: "var(--type-label-line)", letterSpacing: "var(--type-label-tracking)", fontWeight: "var(--type-label-weight)" }],
    eyebrow: ["var(--type-eyebrow-size)", { lineHeight: "var(--type-eyebrow-line)", letterSpacing: "var(--type-eyebrow-tracking)", fontWeight: "var(--type-eyebrow-weight)" }],
    caption: ["var(--type-caption-size)", { lineHeight: "var(--type-caption-line)", fontWeight: "var(--type-caption-weight)" }],
    note: ["var(--type-note-size)", { lineHeight: "var(--type-note-line)", fontWeight: "var(--type-note-weight)" }],
    quote: ["var(--type-quote-size)", { lineHeight: "var(--type-quote-line)", fontWeight: "var(--type-quote-weight)" }],
    price: ["var(--type-price-size)", { lineHeight: "var(--type-price-line)", letterSpacing: "var(--type-price-tracking)", fontWeight: "var(--type-price-weight)" }],
    data: ["var(--type-data-size)", { lineHeight: "var(--type-data-line)", fontWeight: "var(--type-data-weight)" }],
    error: ["var(--type-error-size)", { lineHeight: "var(--type-error-line)", fontWeight: "var(--type-error-weight)" }],
  },
  spacing: {
    "0": "var(--gs-space-0)",
    "1": "var(--gs-space-1)",
    "2": "var(--gs-space-2)",
    "3": "var(--gs-space-3)",
    "4": "var(--gs-space-4)",
    "5": "var(--gs-space-5)",
    "6": "var(--gs-space-6)",
    "8": "var(--gs-space-8)",
    "10": "var(--gs-space-10)",
    "12": "var(--gs-space-12)",
    "16": "var(--gs-space-16)",
    "20": "var(--gs-space-20)",
    "24": "var(--gs-space-24)",
    "30": "var(--gs-space-30)",
    "40": "var(--gs-space-40)",
  },
  borderRadius: {
    "xs": "var(--gs-radius-xs)",
    "sm": "var(--gs-radius-sm)",
    "md": "var(--gs-radius-md)",
    "lg": "var(--gs-radius-lg)",
    "xl": "var(--gs-radius-xl)",
    "pill": "var(--gs-radius-pill)",
  },
  boxShadow: {
    xs: "var(--gs-shadow-xs)",
    sm: "var(--gs-shadow-sm)",
    md: "var(--gs-shadow-md)",
    lg: "var(--gs-shadow-lg)",
  },
  transitionDuration: {
    instant: "var(--gs-motion-instant)",
    fast: "var(--gs-motion-fast)",
    base: "var(--gs-motion-base)",
    slow: "var(--gs-motion-slow)",
    scene: "var(--gs-motion-scene)",
  },
  transitionTimingFunction: {
    standard: "var(--gs-ease-standard)",
    enter: "var(--gs-ease-enter)",
    exit: "var(--gs-ease-exit)",
    precise: "var(--gs-ease-precise)",
  },
} as const

export type GsTheme = typeof gsTheme

const tailwindTheme = {
  theme: { extend: gsTheme },
}

export default tailwindTheme
